# Generated by Django 6.0.4 on 2026-04-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='contact',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='empname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='empno',
            field=models.CharField(default='tidak ada', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
