# Generated by Django 6.0.4 on 2026-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_artikel_contact_artikel_empname_artikel_empno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=20)),
                ('empname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('joined_date', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='empname',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='empno',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='salary',
        ),
    ]
