# Generated by Django 6.0.4 on 2026-04-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_remove_artikel_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='artikel',
            table='artikel',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
