# Generated by Django 6.0.4 on 2026-04-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_employee_joined_date_alter_artikel_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contact',
        ),
        migrations.AddField(
            model_name='employee',
            name='alamat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
